version: '2'
volumes:
    influxdb-data:
    mqtt-data:
    grafana-data:
    fishnet-data:
services:
 # wifi-connect:
 #   build: ./wifi-connect
 #   network_mode: "host"
 #   privileged: true
 #   labels:
 #     io.resin.features.dbus: '1'
  samba:
    #  hostname: samba  # doesn't work
    image: dastrasmue/rpi-samba 
    command:  
      -u "joe:asdfasdf" 
      -s "fishnet-data:/mount/fishnet-data:rw:joe"
      -s "influxdb-data:/mount/influxdb-data:rw:joe"
      -s "mqtt-data:/mount/mqtt-data:rw:joe"
      -s "grafana-data:/mount/grafana-data:rw:joe"
    volumes:
       - 'fishnet-data:/mount/fishnet-data'
       - 'influxdb-data:/mount/influxdb-data'
       - 'mqtt-data:/mount/mqtt-data'
       - 'grafana-data:/mount/grafana-data'
    ports:
    #  - "137:137"
    #  - "137:137/udp"
      - "139:139"
      - "445:445"
    #  - "445:445/udp"
  influxdb:
    build: influxdb
    container_name: influxdb
    # privileged added so usb drive can be mounted.
    privileged: true
    volumes:
        # take care that the mount location "/mnt/influxdb" becomes overwritten
        # by the mount location specified in the influxdb Dockerfile.
        - 'influxdb-data:/mnt/influxdb'   
    ports:
      # The API for InfluxDB is served on port 8086
      - "8082:8082"
      - "8086:8086"
      # UDP Port
      - "8089:8089"
    restart: always
  telegraf:
    # Full tag list: https://hub.docker.com/r/library/telegraf/tags/
    build : telegraf
    pid: "host"
    network_mode: "host"
    privileged: true
    labels:
      io.resin.features.balena-socket: '1'
    depends_on:
      - influxdb
    restart: always
    environment:
       - interval=60s
       - flush_interval=60s
  grafana:
    build: grafana 
    volumes:
       - 'grafana-data:/grafana'  
    ports:
       - "3000:3000"
    depends_on:
       - influxdb
    restart: always
  mqtt:
    image: arm32v6/eclipse-mosquitto
    volumes:
      - 'mqtt-data:/mosquitto'
    ports:
      - "1883:1883"
  fishnet:
    build: fishnet
    volumes:
       - 'fishnet-data:/fishnet'
    ports:
       - "1880:1880"
    depends_on:
        - mqtt
    restart: always
  nginx:
    build : nginx
    depends_on:
      - grafana
      - fishnet
    ports:
      - "80:80"
      - "443:443"
    restart: always
