version: '2'
volumes:
    node-red-data:
    node-red-test-data:
    influxdb-data:
    mqtt-data:
    mqtt-test-data:
services:
  wifi-connect:
    build: ./wifi-connect
    network_mode: "host"
    privileged: true
    labels:
      io.resin.features.dbus: '1'
  samba:
    #  hostname: samba  # doesn't work
    image: dastrasmue/rpi-samba 
    command:  -u "joe:asdfasdf" -s "node-red-data:/mount/node-red-data:rw:joe"  
    volumes:
       - 'node-red-data:/mount/node-red-data'
    ports:
    #  - "137:137"
    #  - "137:137/udp"
      - "139:139"
      - "445:445"
    #  - "445:445/udp"
  influxdb:
    build: influxdb
    container_name: influxdb
    # privileged added so usb drive can be mounted.
    privileged: true
    volumes:
        # take care that the mount location "/mnt/influxdb" becomes overwritten
        # by the mount location specified in the influxdb Dockerfile.
        - 'influxdb-data:/mnt/influxdb'   
    ports:
      # The API for InfluxDB is served on port 8086
      - "8082:8082"
      - "8086:8086"
      # UDP Port
      - "8089:8089"
    restart: always
  telegraf:
    # Full tag list: https://hub.docker.com/r/library/telegraf/tags/
    build : telegraf
    pid: "host"
    network_mode: "host"
    privileged: true
    labels:
      io.resin.features.balena-socket: '1'
    depends_on:
      - influxdb
    restart: always
    environment:
       - interval=60s
       - flush_interval=60s
  grafana:
    build: grafana 
    ports:
       - "3000:3000"
    depends_on:
       - influxdb
    restart: always
  mqtt:
    image: panuwitp/mosquitto-arm
    volumes:
      - 'mqtt-data:/data'
    ports:
      - "1883:1883"
  mqtt-test:
    image: panuwitp/mosquitto-arm
    volumes:
      - 'mqtt-test-data:/data'
    ports:
      - "1884:1883"
  node-red:
    build: node-red
    volumes:
       - 'node-red-data:/data'
    ports:
       - "1880:1880"
    depends_on:
        - mqtt
    restart: always
  node-red-test:
    build: node-red-test
    volumes:
       - 'node-red-test-data:/data'
    ports:
       - "1882:1880"
    depends_on:
        - mqtt-test
    restart: always
  nginx:
    build : nginx
    depends_on:
      - grafana
      - node-red
      - node-red-test
    ports:
      - "80:80"
      - "443:443"
    restart: always
  mosquitto:
    build: mqtt
    ports:
      - "1885:1883"
    restart: always
